### ISSUE TITLE
Unable to deploy to github pages

### ISSUE THREAD

**Issue by mhzawadi** [tadhglewis/issue-status#87]
I have just pulled in upstream changes and now cant deploy them, I get an error

```
> issue-status@0.1.2 predeploy
> npm run build


> issue-status@0.1.2 build
> react-scripts build

Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/matt/git/issue-status/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/matt/git/issue-status/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/matt/git/issue-status/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/matt/git/issue-status/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/matt/git/issue-status/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/matt/git/issue-status/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/matt/git/issue-status/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/matt/git/issue-status/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/matt/git/issue-status/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/matt/git/issue-status/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/matt/git/issue-status/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/matt/git/issue-status/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/matt/git/issue-status/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/matt/git/issue-status/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/Users/matt/git/issue-status/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/matt/git/issue-status/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/matt/git/issue-status/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/matt/git/issue-status/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/matt/git/issue-status/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/matt/git/issue-status/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/matt/git/issue-status/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/matt/git/issue-status/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/matt/git/issue-status/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.7.1
```

**Comment by mhzawadi** [comment]
I have got a deploy, but I have to use `export NODE_OPTIONS=--openssl-legacy-provider`.
That also gives a warning

```
> issue-status@0.1.2 predeploy
> npm run build


> issue-status@0.1.2 build
> react-scripts build

Creating an optimized production build...
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.

Compiled with warnings.

src/components/App.js
  Line 25:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/components/component/index.js
  Line 18:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/components/component/status.js
  Line 14:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/components/component/statuses.js
  Line 1:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/components/components/component/useStatus.js
  Line 4:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/components/index.js
  Line 6:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/footer/index.js
  Line 22:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/header/index.js
  Line 17:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/incidents/incident/index.js
  Line 57:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/incidents/index.js
  Line 22:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/smaintenance/index.js
  Line 22:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/smaintenance/maintenance/index.js
  Line 57:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/status/index.js
  Line 42:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/status/statuses.js
  Line 1:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/components/status/useRefetch.js
  Line 4:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/status/useStatus.js
  Line 4:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/useDidMount.js
  Line 3:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

src/components/useIssues.js
  Line 3:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
File sizes after gzip:
#######50 characters############################

  115.88 KB  build/static/js/2.e3dbd6ac.chunk.js
  3.58 KB    build/static/js/main.8be4dca5.chunk.js
  779 B      build/static/js/runtime-main.6cd9bfb7.js
  696 B      build/static/css/main.3c0748c1.chunk.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment


> issue-status@0.1.2 deploy
> echo 'status.horwood.biz' > ./build/CNAME && gh-pages -d build
```

**Comment by tadhglewis** [comment]
@mhzawadi I'll take a look soon

**Comment by tadhglewis** [comment]
I've done a round of dependency updates and this seems to be fixed - you should also use yarn instead of npm

**Comment by mhzawadi** [comment]
all good now, thanks 👍🏼
